newsletters:
  - identifier: Pycoders Weekly
    source: <admin@pycoders.com>
  - identifier: SE Daily
    source: <erika@softwareengineeringdaily.com>
  - identifier: JavaScript Weekly
    source: <jsw@peterc.org>
  - identifier: O'Reilly Programming Newsletter
    source: <oreilly@post.oreilly.com>
  - identifier: Web Operations Weekly
    source: <peter@webopsweekly.com>
  - identifier: Elixir Radar
    source: <elixir.radar@plataformatec.com.br>
  - identifier: Scala Times
    source: <scalatimes@softwaremill.com>
  - identifier: Ruby Weekly
    source: <rw@peterc.org>
  - identifier: Python Weekly
    source: <rahul@pythonweekly.com>
  - identifier: Barrett Helms
    source: <barrett.helms@technekes.com>

database:
  dev:
    host: db
    port: 5432
    database: parser_dev
    username: postgres
    password: postgres
