version: "2"
services:
  parser:
    build: .
    environment:
      PYTHONPATH: /usr/src/app
    env_file: secrets.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: bin/start.sh

  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
